<?php
/**
 *@author zhaofei
 *@package config
 *@subpackage global config
 */
return array(
  'A_TIME_ZONE_NAME' => 'Asia/Shanghai',
  'A_BLOG_LANGUAGE' => 'zh-CN',
  'A_BLOG_LANGUAGEPACK' => 'SimpChinese',
  'A_VERIFYCODE_STRING' => 'ABCDEFGHKMNPRSTUVWXYZ123456789',
  'A_VERIFYCODE_WIDTH' => 90,
  'A_VERIFYCODE_HEIGHT' => 30,
  'A_VERIFYCODE_FONT' => 'system/defend/arial.ttf',
  'A_DISPLAY_COUNT' => 10,
  'A_SEARCH_COUNT' => 25,
  'A_PAGEBAR_COUNT' => 10,
  'A_COMMENTS_DISPLAY_COUNT' => 100,
  'A_DISPLAY_SUBCATEGORYS' => false,
  'A_RSS2_COUNT' => 10,
  'A_RSS_EXPORT_WHOLE' => true,
  'A_MANAGE_COUNT' => 50,
  'A_EMOTICONS_FILENAME' => 'face',
  'A_EMOTICONS_FILETYPE' => 'png|gif|jpg',
  'A_EMOTICONS_FILESIZE' => '16',
  'A_UPLOAD_FILETYPE' => 'jpg|gif|png|jpeg|bmp|psd|wmf|ico|rpm|deb|tar|gz|sit|7z|bz2|zip|rar|xml|xsl|svg|svgz|doc|docx|ppt|pptx|xls|xlsx|wps|chm|txt|pdf|mp3|avi|mpg|rm|ra|rmvb|mov|wmv|wma|swf|fla|torrent|apk|zba',
  'A_UPLOAD_FILESIZE' => 2,
  'A_USERNAME_MIN' => 3,
  'A_USERNAME_MAX' => 50,
  'A_PASSWORD_MIN' => 8,
  'A_PASSWORD_MAX' => 20,
  'A_EMAIL_MAX' => 50,
  'A_HOMEPAGE_MAX' => 100,
  'A_CONTENT_MAX' => 1000,
  'A_ARTICLE_EXCERPT_MAX' => 250,
  'A_COMMENT_EXCERPT_MAX' => 20,
  'A_STATIC_MODE' => 'ACTIVE',
  'A_ARTICLE_REGEX' => '{%host%}?id={%id%}',
  'A_PAGE_REGEX' => '{%host%}?id={%id%}',
  'A_CATEGORY_REGEX' => '{%host%}?cate={%id%}&page={%page%}',
  'A_AUTHOR_REGEX' => '{%host%}?auth={%id%}&page={%page%}',
  'A_TAGS_REGEX' => '{%host%}?tags={%id%}&page={%page%}',
  'A_DATE_REGEX' => '{%host%}?date={%date%}&page={%page%}',
  'A_INDEX_REGEX' => '{%host%}?page={%page%}',
  'A_INDEX_DEFAULT_TEMPLATE' => 'index',
  'A_POST_DEFAULT_TEMPLATE' => 'single',
  'A_SIDEBAR_ORDER' => 'calendar|controlpanel|catalog|searchpanel|comments|archives|favorite|link|misc',
  'A_SIDEBAR2_ORDER' => '',
  'A_SIDEBAR3_ORDER' => '',
  'A_SIDEBAR4_ORDER' => '',
  'A_SIDEBAR5_ORDER' => '',
  'A_GZIP_ENABLE' => false,
  );
?>